name: .Net CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - uses: actions/checkout@v2

      - name: Install Render CLI
        run: |
          curl -sL https://render.com/install.sh | bash

      - name: Deploy to Render
        run: |
          export RENDER_EMAIL=${{ secrets.RENDER_EMAIL }}
          export RENDER_PASSWORD=${{ secrets.RENDER_PASSWORD }}
          render deployment create --branch=master --file=Dockerfile --name=merc_vista_api
