name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./publish
          github-token: ${{ secrets.GITHUB_TOKEN }}
